# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/01_download_raw_videos.ipynb.

# %% auto 0
__all__ = [
    "download_youtube_video",
    "try_download_youtube_video",
    "download_raw_videos",
]

# %% ../../nbs/data/01_download_raw_videos.ipynb 3
from ..cli import cli
from torch_snippets import *
import subprocess
import yt_dlp


# %% ../../nbs/data/01_download_raw_videos.ipynb 4
def download_youtube_video(url, video_fpath):
    command = ["yt-dlp", "-f", "bestvideo[ext=mp4]", "-o", video_fpath, url]
    subprocess.run(command, check=True)


def try_download_youtube_video(url, video_fpath):
    try:
        download_youtube_video(url, video_fpath)
    except Exception as e:
        Warn(f"Error: {e} @ {video_fpath}")


@cli.command()
def download_raw_videos(annotations_csv_path, folder):
    annotations = pd.read_csv(annotations_csv_path)
    df = annotations[["url", "video"]].drop_duplicates().reset_index(drop=True)
    for ix, row in track2(df.iterrows(), total=len(df)):
        title = row.video
        url = row.url.split("watch?v=")[-1]
        video_fpath = f"{folder}/{title}.mp4"
        if not exists(video_fpath):
            try_download_youtube_video(url, video_fpath)
    else:
        Info(f"Skipping {video_fpath}")
