# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/model/00_linear.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/model/00_linear.ipynb 4
from ..cli import cli
from ..data.dataset import ClipEmbeddingsDataset
from torch_snippets import *
